### ISSUE TITLE
SKT NPC issues

### ISSUE THREAD

**Issue by cgraffeo** [zajako/LineageHD#106]
The following NPCs in SKT don't open a dialogue when clicked on:

- [ ] Dunham
- [ ] Drist
- [ ] Lekman
- [X] -Pledge Master-
- [X] -Elixer Alchemist-
- [ ] Gerard Mercenary Squad
- [ ] Market Teleporter  x2
- [ ] Joel
- [ ] Village Manager
- [ ] Secretary to the Mayor
- [ ] Julie
- [X] Lanore
- [X] Minnie
- [X] Frintezza's Seamstress
- [ ] Pin
- [ ] Guard

**Comment by zajako** [comment]
The npcs that mattered now work, the ones that didn't have been removed. I'm closing this post now.
