### ISSUE TITLE
Cannot Log In on Main Char - Still Broke

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#131]
When I try to log in as Sooleawa I get strange error boxes and client crashes.
Can log in on both alt chr's with no problem.

**Comment by zajako** [comment]
take a screenshot of the strange error boxes please

**Comment by Sooleawa2** [comment]
It's the same one I posted on coolkids on 4/29. You said it was just a bug reporter. I couldn't remember what you called it when I created this.

**Comment by Sooleawa2** [comment]
Sorry, that was on 5/4
