### ISSUE TITLE
Adding multiple stat points causes inability to add remaining points

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#133]
When adding stat points after you have started the game and accepting the dialog box, a new window comes up to add the remaining stat points but you cannot complete the screen or exit the screen without restarting the game.

First Image is of the initial screen (Ctrl+A)

![add-stat-point-bug-1](https://user-images.githubusercontent.com/8341446/59783504-1d2f9f80-9275-11e9-84f1-dc27a6a54533.PNG)

Second image is after you have selected a single stat point and accepted the dialog box. You cannot add stat points in the character menu (Ctrl+A) and when you close it you get stuck in image 3 indefinitely until you restart the client.

![add-stat-point-bug-2](https://user-images.githubusercontent.com/8341446/59783548-37697d80-9275-11e9-93d9-9af90752acb4.PNG)

Third image is after you have closed the stat point distribution and try to distribute the points using the menu on the right side.

![add-stat-point-bug-3](https://user-images.githubusercontent.com/8341446/59783601-5700a600-9275-11e9-98d2-12755386ddcd.PNG)

**Comment by OvahKeel** [comment]
After waiting some period of time the game provides an error

![add-stat-point-bug-4-error](https://user-images.githubusercontent.com/8341446/59783745-b363c580-9275-11e9-8bf7-67e938749bbf.PNG)

**Comment by zajako** [comment]
this is pretty strange, not sure why it is bringing up the stat reset window when you click the plus icon. I'll have to investigate how this is linking the two systems that should be separate.

**Comment by AeacosL15** [comment]
Reached level 51 and tried to add my stat.  It opened up the stat redistribution window, so I added my points into CON again.  Got a message about still having the level up stat, but wildly changed all my stats and wouldn't let me do anything.  Had to restart the game.  When I did it gave me the level 1 buffs, HP, and MP despite still being 51 and stats are all over the place.
![image](https://user-images.githubusercontent.com/54756927/64071068-438b9700-cc37-11e9-8f31-d25ebb8d0867.png)

**Comment by AeacosL15** [comment]
![Lineage 2019-08-31 21-30-26-008](https://user-images.githubusercontent.com/54756927/64071084-9402f480-cc37-11e9-8f9a-99773eb1a525.jpg)

**Comment by zajako** [comment]
I can't seem to duplicate this. I've added 14 stat points, back to back and can't seem to trigger this other window to come up.

**Comment by zajako** [comment]
despite not being able to duplicate this, I found the issue causing it. I've fixed it.

**Comment by zajako** [comment]
sigh, its not working at all now... need to figure out why its taking the bonus points but not saving the stat add.

**Comment by zajako** [comment]
I found why It didn't bring up that window for me, but did for you guys. Apparently it doesn't effect GM's.  My change earlier did fix that though, however, there are some changes to the way base and added stats work in the new client, so it wasn't saving properly. It will be fixed shortly now that I understand the problem.

**Comment by zajako** [comment]
Yay, this ones fixed, and I fixed the broken stats you guys ended up giving yourself. Also it now allows continuous adding of points till you're out. No need to restart after adding each point like on the old client!
