### ISSUE TITLE
When using -pbuff system says nothing happened

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#135]
I am not sure which buff it is related to, SS below.

![pbuff-nothing-happened](https://user-images.githubusercontent.com/8341446/59784295-f3777800-9276-11e9-9143-4fe97341c605.PNG)

**Comment by zajako** [comment]
It appears to be because you don't have a weapon equipped or armor equipped and the spells are included bless weapon and bless armor.
