### ISSUE TITLE
When attacking using ctrl+click or double clicking ctrl and in pvp mode client crashes

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#136]
Client crashes when ctrl+click and attacking or entering pvp mode (ctrl twice) and attacking something.

I am unable to recreate this issue this morning. I did reset to default the play support before I attempted to recreate this issue. I cannot attack anything at this point after resetting the play support to default. I will test further and update.

**Comment by OvahKeel** [comment]
This could possibly be related to issue #145 as I think it's getting stuck in an infinite loop of some sort since the NPC (or player) can never die. Force attacking NPC's seems to be fine with no poly.

**Comment by zajako** [comment]
I can't duplicate this issue, but I believe when I redo the attack code, it should fix it. Redoing the attack code will be covered  in this ticket: https://github.com/zajako/LineageHD/issues/167
