### ISSUE TITLE
Yeti UI mode resets window size to 1280 x 720

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#137]
When using selecting the Yeti UI it resets the window size to 1280 x 720. Window size can be changed back to 1920 x 1080 in this mode but every time you click on "UI settings" tab it will reset back to 1280 x 720 unless you are in the "Standard" or "Modern" UI setting.

**Comment by zajako** [comment]
Yeti Mode is simple mode, I'm pretty sure its used for streaming to mobile. It changes resoultion to be easier to use on mobile i believe, either way I can't fix this as its built into the client.
