### ISSUE TITLE
Green leaf (buff?, not sure what it is) is missing info in Yeti mode

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#139]
Green leaf on top left of buffs bar in Yeti UI mode is showing %d% instead of a value.

![missing-information](https://user-images.githubusercontent.com/8341446/59785816-adbcae80-927a-11e9-9c9f-98045f70b218.PNG)

**Comment by zajako** [comment]
This is no longer showing up, I'm marking it fixed
