### ISSUE TITLE
CDK missing sprite/animation in certain position

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#141]
CDK is missing a sprite when faced left and standing still. (sword disappears)

![missing-sprite](https://user-images.githubusercontent.com/8341446/59786253-b06bd380-927b-11e9-8901-a017a1aa588a.PNG)

**Comment by OvahKeel** [comment]
This applies to a variety of poly's I tried, some are missing sprites while attacking and show the X, hard to get screen shot of.

**Comment by zajako** [comment]
Most of the cases where this happens should be fixed, however the cdk one is not, and may require to be replaced with just lightning dk or something. I'll leave this ticket up but move it to the next milestone as the morph still works.

The other polies that are hard to duplicate it with are most likely fixed as its most likely proc animations that were broken. I've now fixed all of those.
