### ISSUE TITLE
Wrong animation/sprites/models for a variety of monsters in warp 8

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#144]
Many of the monsters seem to have the wrong models. Example below: Castalia. There are quite a few others in warp 8 as well that are incorrect.

![wrong-model](https://user-images.githubusercontent.com/8341446/59788618-f9725680-9280-11e9-89a8-122c8c54e486.PNG)

**Comment by zajako** [comment]
This is a known issue for fixing mobs of unsupported sprites.
