### ISSUE TITLE
polymorph attacking is extremely laggy

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#145]
When attacking monsters the game becomes extremely laggy. Does not show any animations but a few of the sounds play. Changing resolution does not seem to help, neither does full screen. Game "comes back" after monster is dead.

**Comment by OvahKeel** [comment]
After some further testing, non-polymorphed attacking is fine. Using ANY poly causes this to happen. The screen gets stuck until the monster dies. Once the monster has died the screen comes back normally. Clicking off the target and then back on to it causes the client to update and you can move/see attacks but once you start attacking again the screen will still freeze up.

**Comment by zajako** [comment]
This should be fixed now.
