### ISSUE TITLE
ID scroll causes client crash

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#149]
After clicking on an ID scroll and identifying an item, client crashes to desktop.

**Comment by OvahKeel** [comment]
Actually, this is true for ANY item. All of the item's that are ID'd in my inventory are showing as blessed if they are ID'd. None of my items are "normal" that have been identified.

**Comment by zajako** [comment]
I've fixed this bug, it no longer causes a crash. Please open up a new issue for all items showing up as blessed.
