### ISSUE TITLE
Being paralyzed does not stop attack animation (or hit animation of target)

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#152]
When attacking a target (monster) and you get paralyzed from their poison you do not stop attacking but you do not deal any damage either. Animations of target still get hit and animation for attacking still continues (but no damage from the attack is dealt to target).

**Comment by zajako** [comment]
This will be fixed when I redo the attack system in this issue: https://github.com/zajako/LineageHD/issues/167
