### ISSUE TITLE
Jin morph super attack speed

### ISSUE THREAD

**Issue by OvahKeel** [zajako/LineageHD#153]
Not sure if it's supposed to be like this, but it hits like 20 times for one displayed hit.

https://www.dropbox.com/s/iicbo9rtn4krf7r/jin-morph-bug.mp4?dl=0
vs CDK
https://www.dropbox.com/s/oq1nrxc1a8et7ex/cdk-working-now.mp4?dl=0

**Comment by zajako** [comment]
This should be fixed now
