### ISSUE TITLE
Alt-Tab and Back

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#179]
Alt-Tab to another application then back to the game causes HP/MP bar and NPC names to be in the wrong place on the screen.  Windows resolution is 2560x1440

**Comment by AeacosL15** [comment]
Changing settings to windowed mode and back to full screen resets to correct size/locations

**Comment by zajako** [comment]
Sadly this is an issue in the binary file of the game and will require a client binary update to fix. So likely down the line after the game goes live. I believe this bug only happens in full screen mode as well so if you use windowed mode at 1080 resolution it shouldn't have the issue.

I'm gonna close this issue as its currently unfixable.
