### ISSUE TITLE
All Chests show as open when they are closed.

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#182]
Mini-map scale is larger than mini-map window ... current location arrow travels around the screen.

Once completed boxes are shown as open, but game allows you to still "open" one.

![Lineage 2019-08-31 23-46-20-027](https://user-images.githubusercontent.com/54756927/64071916-c66a1d00-cc4a-11e9-9a02-4dd8476402c2.jpg)

**Comment by AeacosL15** [comment]
Make that all Ivory Tower daily instances.

**Comment by AeacosL15** [comment]
Add Valakas' Lair to the map issues

**Comment by AeacosL15** [comment]
Pot of Gold chests in the Leprechaun Hunt instance work, but are also showing as open with no name.

**Comment by zajako** [comment]
Yeah they changed the status code for open and closed to be backwards. will fix it shortly.

**Comment by zajako** [comment]
I've got them showing up as closed, but now they don't open lol... They give you items, but appear to be closed still. will try again shortly.

**Comment by zajako** [comment]
It seems the action to open the chest no longer works. The action to close it works, but open however doesn't.  The fix for it will have to be to just despawn the chest right after you open it. Next test server restart should implement that.
