### ISSUE TITLE
Breeding Grounds

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#183]
When clicking on a Breeding Grounds portal, you receive a warning about account hijacking.

![Lineage 2019-09-01 00-06-40-793](https://user-images.githubusercontent.com/54756927/64072074-68d7cf80-cc4e-11e9-86a4-e1d8cc04d8af.jpg)

**Comment by zajako** [comment]
This is just a text string issue, did it let you enter if you said confirm?

**Comment by AeacosL15** [comment]
No, it just closed the Notice window

**Comment by zajako** [comment]
I've fixed the message, however I'll have to figure out why its not allowing you to enter in after clicking confirm.

**Comment by zajako** [comment]
I've put in some lines of code that should fix this with the next restart. Putting it in queue for verification.

**Comment by zajako** [comment]
I've verified this is now fixed!
