### ISSUE TITLE
EXP Growth Rooms

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#185]
Only Floor 1 is available.  All floors are shown as options, but floors 0, 2, and 3 give you a message - "This growth room is currently disabled."

**Comment by AeacosL15** [comment]
Same for SXP growth rooms

**Comment by zajako** [comment]
Growth rooms other than floor 1 are disabled on the test server, because I want you guys to level up and test for me the normal way lol. They do work however, I've tested them otherwise.
