### ISSUE TITLE
TOI 21 Black Screen

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#186]
TOI 21f is dark again.  Can't move.

![Lineage 2019-09-01 09-16-18-174](https://user-images.githubusercontent.com/54756927/64077850-d1986980-cc99-11e9-88d9-7c4d40f8358a.jpg)

**Comment by zajako** [comment]
How did you get to toi21?

**Comment by AeacosL15** [comment]
I used a 21f scroll.  I've not been able to find any of the stairs/portals yet.

**Comment by zajako** [comment]
Okay, this map is for some reason completely broken. The weird thing is, its the same everything as all the x1 maps and they all work.

**Comment by zajako** [comment]
This one is frustrating, it was working at some point, I tested every single floor. I've also replaced the map files several times and its still blank. This is a very very strange bug.

**Comment by zajako** [comment]
Gonna find a way to make it so it skips floor 21

**Comment by zajako** [comment]
I've adjusted it so that the boss portal on 20 will move you to 22 and the toi 21 scroll takes you to 22.

**Comment by zajako** [comment]
I've verified that now floor 21 is skipped for now, until someday when I can force it into compliance..
