### ISSUE TITLE
Orc Forest

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#189]
Just outside of Orc Town to the west ... Orc Forest has been clear-cut and is now just a field.

![Lineage 2019-09-01 09-39-43-347](https://user-images.githubusercontent.com/54756927/64078170-e88c8b00-cc9c-11e9-8d53-a7b808d66029.jpg)

**Comment by zajako** [comment]
This will be fixed with the change that fixes the orc fortress here: https://github.com/zajako/LineageHD/issues/191
