### ISSUE TITLE
Orc fortress western walls invisible.

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#191]
Orc castle is missing it's western defenses (walls) and the gate image is showing the "red X" which you can't Ctrl-Click to attack/break.

![Lineage 2019-09-01 09-57-13-532](https://user-images.githubusercontent.com/54756927/64078354-45894080-cc9f-11e9-872f-abff00281f84.jpg)

**Comment by zajako** [comment]
I fixed the door. The western walls are at least there invisibly. Preventing anyone from walking into the orc fort area.

I can't really fix this as of yet, so I'm gonna mark it as closed as it will be fixed when the map is upgraded, which is already planned.
