### ISSUE TITLE
Character not completely logged out?

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#192]
Created an Elf, logged out, create a Dark Elf, and I can still see my Elf on screen even after a couple minutes.

![Lineage 2019-09-01 10-43-04-306](https://user-images.githubusercontent.com/54756927/64078872-fd215100-cca5-11e9-91d9-0b65e2b694fc.jpg)

**Comment by zajako** [comment]
This happened to me too. seems to be when you choose change character from the restart menu.

**Comment by zajako** [comment]
I've put in a fix for this, pending restart.

**Comment by zajako** [comment]
This appears to be fixed now. If it happens again, please re-report it.
