### ISSUE TITLE
Lost Bookmarks

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#195]
I had 7 or 8 bookmarks that I've used several times, but now they're not showing up.

**Comment by AeacosL15** [comment]
I changed the drop down and found some of them.

![Lineage 2019-09-01 14-47-57-076](https://user-images.githubusercontent.com/54756927/64081512-c4926f00-ccc7-11e9-9620-c753071c2474.jpg)

**Comment by AeacosL15** [comment]
This appears for every drop down option, except "All"

**Comment by Sooleawa2** [comment]
Thanks for the tip. Same thing happened to me. Now I can see them again.
