### ISSUE TITLE
Underground Passage

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#196]
Missing mini-map and seems you can't get through.  Path seems to be blocked.

Staying to the right, I hit this block.
![Lineage 2019-09-01 15-03-04-981](https://user-images.githubusercontent.com/54756927/64081706-4c797880-ccca-11e9-910b-ee3dc817f842.jpg)

Back tracked and the other path to the left is also blocked.
![Lineage 2019-09-01 15-03-36-523](https://user-images.githubusercontent.com/54756927/64081712-58653a80-ccca-11e9-9790-fce6fdbedaeb.jpg)

**Comment by zajako** [comment]
Use the command -loc and let me know what it says. So I can repair this map.

**Comment by AeacosL15** [comment]
1st screen shot:
32760, 32805, 14
32759, 32805, 14
32758, 32804, 14
32757, 32804, 14

2nd screen shot:
32657, 32801, 14
32656, 32801, 14
32655, 32801, 14

**Comment by zajako** [comment]
Thanks, I'll have to fix this by replacing the map I guess.

**Comment by zajako** [comment]
This map is no longer used, which is why its blocked.
