### ISSUE TITLE
Psy poly scrolls

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#198]
turn you invisible.  LOL

![Lineage 2019-09-01 16-28-07-123](https://user-images.githubusercontent.com/54756927/64082507-b9ded680-ccd5-11e9-8fe7-36113c726268.jpg)

**Comment by zajako** [comment]
okay, those items will likely have their poly ability removed, as the psy sprite is no longer in the client. It will be added back eventually when the sprites are re-added.

**Comment by zajako** [comment]
After test server restart, the scroll won't work anymore, and will make it work in the future when the sprite is added. I can't add it yet as an HD sprite hasn't been made for it yet.
