### ISSUE TITLE
Launcher not resizing correctly

### ISSUE THREAD

**Issue by Dmlawrence925** [zajako/LineageHD#199]
When resizing the launcher window the client doesnt resize correctly and can move items off the clickable screen. Scroll bars do not appear to allow you to get to these areas. You have to adjust the window again to get it back.
![Capture1](https://user-images.githubusercontent.com/7517308/64084958-e1e23000-ccfd-11e9-830b-63360cecc760.PNG)
![Capture2](https://user-images.githubusercontent.com/7517308/64084959-e3135d00-ccfd-11e9-818a-b36a24ac960b.PNG)

**Comment by zajako** [comment]
This is a good issue, and could be a problem on computers where the resolution is too small or shaped wrong.  I believe it is supposed to be forced to the aspect ratio for 1080/720. Try pressing Alt + Enter and seeing how it looks in full screen mode.  I do intend on fixing this for windowed mode at some point, but its low priority atm, so I've set the milestone to be post-release.  Also if you let me know your character name I can give you the bounty reward for it. (you can send me a pm on discord or in game if you catch me there)
