### ISSUE TITLE
Can't sell items to shops

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#202]
Can't sell pots, scrolls, gems, armor or weapons to any of the shops.

**Comment by zajako** [comment]
is it that you can't sell to the shops or that the shops don't have a sell button. Try pandora or caroline, they both have sell buttons and should work.

**Comment by Sooleawa2** [comment]
Both, regular shops have the sell button but I could not sell anything. Weapons shops do not have sell button.

**Comment by Sooleawa2** [comment]
Tried Pandora like you suggested and was able to sell items.

**Comment by zajako** [comment]
Which npcs had the sell button, but did not allow you to sell any items?  Did it just have an empty sell window? As that could just mean that npc didn't accept any of the items you were selling.

**Comment by Sooleawa2** [comment]
Couldn't find Caroline but Pandora buys weapons, armor and many other items

**Comment by zajako** [comment]
this should be functioning how it does on live then. You can only sell the items that the specific npc purchases to that npc.
