### ISSUE TITLE
Pagan Temple - Client Crashed

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#204]
NPC (Pagan Follower) text seems to be fixed, but I clicked on "I'm ready" and the client closed/crashed with no error message.  I've not been able to log into my knight since (client crashes), but I can log into other characters.

**Comment by zajako** [comment]
Mapid: 410 is not working, will look into this and fix it.

**Comment by zajako** [comment]
Will also add getback for the proper zone.

**Comment by zajako** [comment]
this is now fixed
