### ISSUE TITLE
Lag (maybe soulshots or LDK)

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#207]
Had chat lag but stopped when I closed old client.

Have severe animation lag when attacking (using drag & drop target lock). Did not change when old client was closed. Difficult to take on more than 1 or 2 mobs at a time. Screen is frozen until mob ends then it will update. Makes it very tough to survive.

**Comment by AeacosL15** [comment]
I notice this when in CDK morph and using soul shots.  If I turn soul shots off it gets much better.

**Comment by zajako** [comment]
Soul shots don't have animations, so they shouldn't be causing lag, if this is the case, I need to look into why soul shots are causing lag otherwise.

**Comment by Sooleawa2** [comment]
I tried hunting FV with soul shots last night and had to stop using them because of animation lag.

**Comment by zajako** [comment]
soul shots are showing an animation?

**Comment by zajako** [comment]
I just checked the code, and there should be no soulshot animations to cause any lag...

**Comment by AeacosL15** [comment]
I don't see any animation, but there's something about soul shots that will cause your screen to freeze up.  Some morphs are worse than others.  I often still here sounds in the background and whatever I'm hitting eventually dies, but the screen is frozen until it's dead ... then there's some accelerated movement of anything else that came on-screen until it has a chance to catch up.

Others have mentioned lag issues as well on global chat.  My first comment to them is to stop using soul shots if they are.  Most of the time they say this resolved their issue.

**Comment by zajako** [comment]
I'll get to the bottom of this.

**Comment by zajako** [comment]
Well, the bug is temporarily fixed, by making it so you don't use up the soul shots.  I'll find a way to fix the soul shot consume packets so they don't cause this lag.  Enjoy unlimited shots until then!  (also enjoy no lag while hunting caused by them)

**Comment by zajako** [comment]
I've put in some code to try to fast track the packets and ensure that the soulshots don't cause lag with it. I'll restart and I'll need help knowing if its fixed as I've never had this issue.

**Comment by zajako** [comment]
I've implemented this fix and it seems to work great. Use soulshots as much as you want, and you should have no lag caused by it.  Create a new ticket if you still seem to have the SS lag.
