### ISSUE TITLE
Giran weapon shop (Werner) not working

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#208]

**Comment by zajako** [comment]
Please provide more information as to how its not working. Can you not click on it? Does it bring up an empty text box? Need more details.

**Comment by Sooleawa2** [comment]
Sorry, nothing happens when you click on him. I'll update it when I get home.
    On Monday, September 2, 2019, 03:45:49 PM EDT, zajako <notifications@github.com> wrote:  
 
 
Please provide more information as to how its not working. Can you not click on it? Does it bring up an empty text box? Need more details.

**Comment by zajako** [comment]
This should be fixed with the next restart, along with vergil the armor shop
