### ISSUE TITLE
Orim's Sin - Instance Key

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#210]
Did it on Easy for the 2nd time, got the message that I received the key but didn't.  Lag maybe, I got the keys in all other instances and Orim's Sin my 1st time.

![Lineage 2019-09-02 10-43-30-843](https://user-images.githubusercontent.com/54756927/64125256-04606180-cd6f-11e9-86ae-387de3c11f4c.jpg)

**Comment by zajako** [comment]
This rarely happened on live too. I never did get the chance to figure out why. I'm gonna push this to the post release milestone to take a look at it sometime when I get the chance, but I don't think it happens often enough to be prioritized for before release.

**Comment by zajako** [comment]
the key not delivering seems to be based on inventory, I'm closing this ticket as It is preventable by keeping enough inventory before going in.
