### ISSUE TITLE
Can't wear pants in pants slot

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#215]
Bought an army pack to try wearing belt and pants (leggings) ... didn't work.  :(

**Comment by zajako** [comment]
did it equip to belt slot, orjust not at all?

**Comment by AeacosL15** [comment]
It went to belt slot.

**Comment by zajako** [comment]
okay thanks, yes currently all the pants items are not moved over to pants slot yet, I'll do this soon.

**Comment by zajako** [comment]
Pending Test server restart this is fixed. All pants are switched to the pants slot.
