### ISSUE TITLE
Halloween Happening Instance map causes crash and won't allow login

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#216]
MapID: 8267

**Comment by AeacosL15** [comment]
That's odd, I successfully completed it this morning.

**Comment by zajako** [comment]
it might be a specific map in that set of maps. I'll look into it, thanks for the update

**Comment by AeacosL15** [comment]
Ugh, was running this instance again and it was going fine ... until I hit the wrong key and turn soulshots on.  Screen instantly froze up, but I could still hear the sounds of me hitting for a minute until the client crashed.  Now I can't log into Aeacos.  :(

**Comment by zajako** [comment]
I've now put in a fix for this.

Also i've made it, so that if there are any issues with entering a map at login, it should now teleport you to skt before login to prevent a crash.

Most cases it should teleport you back after successfully logging in to allow you to return to the map you were.
