### ISSUE TITLE
Bow attack animation missing if you run out of arrows. (still does damage though)

### ISSUE THREAD

**Issue by rayruben** [zajako/LineageHD#217]
no attack animation on elf. all arrows gone from inventory too

**Comment by zajako** [comment]
Damage still happens, just no arrow flying by.

**Comment by rayruben** [comment]
yes, still dmg mops no arrows or attack motion on toon. just stands there

**Comment by rayruben** [comment]
not just no arrows in inventory, arrows removed from inventory when restart. when purchased, arrows look like this in inventory. attack animation works though.
![Lineage 2019-09-02 16-40-57-355](https://user-images.githubusercontent.com/52116056/64133051-d47e8180-cda1-11e9-919f-3e43b2a20728.jpg)

**Comment by zajako** [comment]
werid, let me know if they are removed when you shoot them and if you have animation again while you have the arrows.

**Comment by zajako** [comment]
I've tested and it seems this bug is fixed now.

**Comment by zajako** [comment]
seems this bug has re-surfaced, I'm reopening it.

**Comment by zajako** [comment]
This is fixed again...
