### ISSUE TITLE
Closing world map

### ISSUE THREAD

**Issue by Samtook** [zajako/LineageHD#218]
When clicking the world map, I then try to close using the X at the top right. The game crashes back to desktop.

**Comment by zajako** [comment]
Please give more details, which map were you on, etc. As this doesn't happen every time.  I need to be able to duplicate it so I can verify when its fixed.

**Comment by Samtook** [comment]
The map button on the bottom of the client with the other game buttons.  It opens the world map.

**Comment by zajako** [comment]
Yes, what map were you in, as in zone or hunting area.

**Comment by Samtook** [comment]
OK.  I am in the start area. by the training dummies.  Right were you are standing.  ;)

**Comment by zajako** [comment]
hmm, opening and closing the map here doesn't seem to crash me, but clicking the zoom button does.  I'll investigate further when I have a chance.

**Comment by Samtook** [comment]
you see me in the start area?

**Comment by Samtook** [comment]
It was using the global map in the new char start area.

Once I was in Aden, the global map worked.
