### ISSUE TITLE
Dream Island background is blank

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#221]
Went to Dream Island to kill the elementals and noticed the background is blank when crossing the bridges.  It's been a while, but I thought it was a sky/clouds background.

![Lineage 2019-09-03 18-57-21-583](https://user-images.githubusercontent.com/54756927/64216385-43c9a380-ce7e-11e9-8b9d-5937daca880d.jpg)

**Comment by zajako** [comment]
Sky castle is also blank. I'll fix that at the same time I fix this.

**Comment by zajako** [comment]
This is fixed now
