### ISSUE TITLE
Can't re-run daily instances for GC

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#222]
Tried to re-run the Ivory Tower and Thebes instances for GC.  Wasn't able to and received odd messages.  Clicking the prompts just closed the message windows.  I had GC in my inventory and in storage.

Hardin's Lab
![Lineage 2019-09-03 19-03-54-108](https://user-images.githubusercontent.com/54756927/64216461-9b680f00-ce7e-11e9-8f0d-a23db32d7418.jpg)

Orim's Lab
![Lineage 2019-09-03 19-03-59-616](https://user-images.githubusercontent.com/54756927/64216489-b33f9300-ce7e-11e9-8443-604e53d52614.jpg)

Orim's Sin
![Lineage 2019-09-03 19-04-03-138](https://user-images.githubusercontent.com/54756927/64216546-eaae3f80-ce7e-11e9-91ca-f81021fa0375.jpg)

Alter of Osiris
![Lineage 2019-09-03 19-04-06-765](https://user-images.githubusercontent.com/54756927/64216551-eeda5d00-ce7e-11e9-89a5-de7ba602e025.jpg)

Pharaoh's Tomb
![Lineage 2019-09-03 19-04-10-973](https://user-images.githubusercontent.com/54756927/64216555-f26de400-ce7e-11e9-8357-1cd5c996116f.jpg)

**Comment by zajako** [comment]
Code for this is now in place, with next restart will need to verify.

**Comment by zajako** [comment]
This works, however the text is incorrect. It will be fixed with the next restart.

**Comment by zajako** [comment]
Apparently despite adding the new lines to the end with a lot of padding, the client can't read them.   I'll have to find another location to put these lines and adjust again..

It does however work, you just have to press Confirm to pay gc to reset. I'll make another attempt to fix the text soon.

**Comment by zajako** [comment]
ARG its still blank... even after hanging the ids... It doesn't make much sense, considering that the string numbers its referencing should be there, gotta debug this a bit better and figure it out.

**Comment by zajako** [comment]
This is now fixed by converting the string variables to a new type used in the new client.
