### ISSUE TITLE
EXP Growth Room

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#225]
Entered the 1x EXP growth room last night (after the daily reset) to get my 1 hour of EXP.  Came home from work today and I was still in the EXP room sitting at level 115 with -1124.9%.  Went to the SXP room and had about 22 minutes still left on my timer.  Restarted the client, went back to both rooms, and still showed 22 minutes in both rooms.

**Comment by zajako** [comment]
Pretty sure this was a bug due to you hitting level 115, which broke your client. Please let me know with a new ticket if it happens again.
