### ISSUE TITLE
Can't login after using b-tele

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#226]
Used a blessed teleport scroll to my Talking Island Dungeon bookmark (which I've used before several times) and client shut down.  I can log into other characters, but not my knight (Aeacos).

**Comment by zajako** [comment]
Try this bookmark again and let me know. It might have been a login prevention from something else.

**Comment by AeacosL15** [comment]
I think we can close this one ... used my bookmark a couple times without issue.  Looks like it was related to the experience problem.
