### ISSUE TITLE
Can't store Vitality Coins

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#227]
They're not showing up in the list of items I can store in my bank/dwarf.

**Comment by zajako** [comment]
code for this is in place and will be verified with the next restart.

**Comment by AeacosL15** [comment]
Still not seeing them in my inventory window as an option to store them in the dwarf.

**Comment by zajako** [comment]
okay, thanks for testing this for me, I must have missed a spot in the code, as there are multiple places for it.

**Comment by zajako** [comment]
This should be fixed with the next restart. Pushing to Pending

**Comment by zajako** [comment]
Sigh... Still not showing up in the menu. I put in an exception for it, but it must be in another place...

**Comment by zajako** [comment]
I've got a fix on deck for this now.

**Comment by zajako** [comment]
This is verified as fixed now.
