### ISSUE TITLE
Level 115 crash and negative experience

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#228]
Logging in at level 115 often crashes the client and levels over 100 indicated having negative experience.

For the record ... I broke the level cap!  :P

![Lineage 2019-09-04 23-58-29-310](https://user-images.githubusercontent.com/54756927/64313230-a307e080-cf70-11e9-8de7-0ae6545b9172.jpg)

**Comment by zajako** [comment]
I've put in the code that should solve this, after a restart of test, moving it to a stage for verification.

**Comment by zajako** [comment]
This is now verified to be fixed! Level up to 115 all you like now!
