### ISSUE TITLE
Reaper's spell ability

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#230]
Not able to learn spells as Reaper, using a spellbook gives the message that my spell level is too low.  When I open the spell window, I still get the screen as if I was still a knight.
![Lineage 2019-09-05 00-24-30-197](https://user-images.githubusercontent.com/54756927/64314343-57573600-cf74-11e9-862d-473621b4787f.jpg)

Logged out and restarted the client.  I now see the full spell screen, but still get the message that my spell level is too low.  Not sure if it's a Reaper issue or known issue with learning spells.
![Lineage 2019-09-05 00-28-43-438](https://user-images.githubusercontent.com/54756927/64314347-5c1bea00-cf74-11e9-841f-554678b63ac0.jpg)

**Comment by zajako** [comment]
On old client, (L1.5 Live)  it requires relogging in to change the spell window too, this is due to the class being set when you view character select. As for not being able to learn the books, i'll look into this soon.

**Comment by zajako** [comment]
This issue is already fixed. It was just the level requirements were higher than expected. I'm closing this issue.
