### ISSUE TITLE
Base stats and level up points

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#232]
It appears that it will allow me to add level up stat points to stats that are already 25 base.

![Lineage 2019-09-05 19-03-47-584](https://user-images.githubusercontent.com/54756927/64391960-51169780-d010-11e9-81d0-7b6eea57f236.jpg)

![Lineage 2019-09-05 19-03-57-061](https://user-images.githubusercontent.com/54756927/64391963-5542b500-d010-11e9-903b-838f1f3cffd8.jpg)

**Comment by AeacosL15** [comment]
I get a message that "The maximum stat value is 45.  Please choose a different stats."

![Lineage 2019-09-05 19-08-36-917](https://user-images.githubusercontent.com/54756927/64392045-ac488a00-d010-11e9-8d50-ba58b1300a52.jpg)

**Comment by AeacosL15** [comment]
Logged out, back in, and tried to add to a stat below 25 (STR was showing 21) ... got the same error message.

![Lineage 2019-09-05 19-11-18-022](https://user-images.githubusercontent.com/54756927/64392164-224cf100-d011-11e9-907e-f8279ad08864.jpg)

Logged out, back in, and added point to DEX (currently at 17) - SUCCESS

Logged out, back in, and tried STR again - ERROR

**Comment by zajako** [comment]
Unequip your gear see if it’s actually 25. Or use -stats

**Comment by AeacosL15** [comment]
Good call, -stats showed STR at 16 base.  Removed all my gear and was able to add points to STR all the way up to 25 base.

Odd behavior, but it worked.  :)

**Comment by zajako** [comment]
some of the lower level gear removes str points to weaken you.

**Comment by zajako** [comment]
I've pushed an update to the text message to make it say 25 instead of 45 as well, closing this ticket as this issue should be all fixed up.
