### ISSUE TITLE
Talking Island Causes your character unable to login

### ISSUE THREAD

**Issue by keblrelf** [zajako/LineageHD#235]
so I donated to get happy buff. tele to talking island and game crashed. when I logged back in I cant pick keb  it just keeps crashing. I can pick other to chars. but not keblrelf  so hes stuck in ti:/

**Comment by zajako** [comment]
I've fixed this so that TI takes you to SKT after logout, with the next restart.

**Comment by zajako** [comment]
This should be fixed now. Closing the ticket.
