### ISSUE TITLE
Event Dragon Weaps & PEN

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#239]
-stats is showing PEN: 0 for a level 40 dragon weapon.

**Comment by AeacosL15** [comment]
Level 40 wave axe on live gives 600 PEN, but showing 0 PEN on test.

**Comment by zajako** [comment]
Fixed this bug.... was a copy pasta gone wrong.. the pen was being overwritten by the player dmg that is currently un-used
