### ISSUE TITLE
Forgotten Island NPCs

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#242]
None of the NPCs work.  The shop will talk to you, but doesn't give you an option to buy anything.  Neither of the teleport NPCs will talk to you.  You get the lips icon, but clicking on them doesn't do anything.

**Comment by zajako** [comment]
please give the npc names so that I can look them up properly

**Comment by AeacosL15** [comment]
Lucky - Teleporter in a shack in the middle of the map.
Ishiris - Teleporter on far west of the map.
Tilon - Shop on far west of the map.

**Comment by zajako** [comment]
Thanks, how did you manage to leave the island if the npc didn't work?

**Comment by zajako** [comment]
You answered this in global, you used breeding grounds portal to then use -warp from.

**Comment by zajako** [comment]
This is now fixed!
