### ISSUE TITLE
Client crashes when switching to character played before

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#245]
If I play knight, I can switch to another character ... but if I switch back to knight, client crashes and I have to restart the game.

**Comment by zajako** [comment]
I can't seem to duplicate this.  Does it happen to you every time or was this a one time thing?

**Comment by AeacosL15** [comment]
Seems to happen every time ... doesn't seem to matter which character either.  If I've played it before in that gaming session, switch, and go back it crashes.

**Comment by zajako** [comment]
This appears to be fixed as we tested in game moments ago. Closing it.
