### ISSUE TITLE
Behemious & Silveria

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#250]
Can't seem to find a way to get there since Matt (teleport NPC in SKT) won't take you there.

**Comment by zajako** [comment]
I'll add them to -warp to make this more accessible. You can however travel to them manually on the maps.

**Comment by zajako** [comment]
After restart the warp commands allow 11 Behemious and 12 Silveria

**Comment by zajako** [comment]
Verified this is working now.
