### ISSUE TITLE
New Sky Mobs

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#256]
You have to use Ctrl to attack the Dark Elves (except Sorcerer) inside the castle.

Orc Archers shoot the red X's.

**Comment by zajako** [comment]
Okay, can you please list the specific names of the ones that you have to hit control?

**Comment by AeacosL15** [comment]
Dark Elf Swordsman
Dark Elf Spearman
Dark Elf Shooter

![Lineage 2019-09-10 19-16-40-902](https://user-images.githubusercontent.com/54756927/64659471-93b9e480-d401-11e9-9bd7-97e71446e811.jpg)

**Comment by zajako** [comment]
Fixes for all of these mobs and the arrows of all the mobs in sky are pushed with the next restart of test.

**Comment by zajako** [comment]
Confirmed this is now fixed.
