### ISSUE TITLE
Pandora jewel upgrades

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#257]
The option in the text is available, but when the upgrade screen appears you can't choose anything to upgrade.

![Lineage 2019-09-10 19-35-04-671](https://user-images.githubusercontent.com/54756927/64659630-6457a780-d402-11e9-9c8d-bd3326ea6596.jpg)

**Comment by zajako** [comment]
I've fixed this text file. However I discovered a bug when clicking the now working links. Fixing that now.

**Comment by zajako** [comment]
This is now fixed.
