### ISSUE TITLE
EXP Growth Room

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#264]
Something's still bugged with the EXP growth room.  I think it has something to do with calculations when you're level 100+.  My experience gain is crazy fast ... gained multiple levels in an hour.  It also didn't kick me out after an hour ... the timer bugged out and is now showing I have over 71,000 minutes remaining.

I caught it before I hit 115 this time.  I'll wait to tier up until you're on and can look at things on your end while I'm in there.

**Comment by AeacosL15** [comment]
Well, the timer seems to be an issue for my level 6x dark elf as well.  He's been in there all night long.  Exp gains at least seem to be what I would expect and not the accelerated rate that my level 100+ character was seeing.

**Comment by AeacosL15** [comment]
Also got the following error ... I assume it's related.

![Lineage 2019-09-13 17-50-57-705](https://user-images.githubusercontent.com/54756927/64899100-5f3b6800-d64f-11e9-8375-63a03460b325.jpg)

**Comment by zajako** [comment]
I believe this could be related to a memory error that was happening.  I'm gonna close it for now, but if it happens again please let me know.
