### ISSUE TITLE
Mainland Caves

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#265]
With random teleport scrolls working, I was able to pass the blocked sections of the Underground Passage and get to the bottom entrance of MLC to kill a few Death Knights & Necromancers.  Some of the floors are bugged, but it seems only certain sections of the floors.  I was able to random teleport on the bugged floors to find areas that were ok and made it up to the 4th floor.  MLC 7f seemed to be ok, but:
MLC 6f
![Lineage 2019-09-13 19-48-20-180](https://user-images.githubusercontent.com/54756927/64901600-19879b00-d661-11e9-9671-5254a5284d3e.jpg)

MLC 5f
![Lineage 2019-09-13 19-49-59-312](https://user-images.githubusercontent.com/54756927/64901603-20161280-d661-11e9-8560-73630393902f.jpg)

MLC 4f
![Lineage 2019-09-13 19-52-29-544](https://user-images.githubusercontent.com/54756927/64901604-25735d00-d661-11e9-86ac-d2f66de4163d.jpg)

**Comment by zajako** [comment]
Mainland Caves was removed in the newer Lineage versions, and thus is being removed here. I'll be adapting it and the maps for it as needed when doing the new pathway maps.
