### ISSUE TITLE
Spell Books tied to level

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#266]
Higher level spell books are tied to character level and not magic level

**Comment by Sooleawa2** [comment]
Forgot that they were. A mage is supposed to be able to learn all 10 spell levels when they reach lvl 40. However, I could not use any level 7 books until I hit lvl 50, I could use lvl 8 & 9 books at somewhere around 53-54. I'm lvl 76 and says "You can not learn this magic because the magic level is low." when I click on mass slow book.

**Comment by zajako** [comment]
Lineage Live server changed this after they closed there servers in usa. This update is matching it with the new standard for spell levels. Which puts learning level 10 magic at level 80. Here are the spell levels for standard magic levels:

Wizard, Reaper:  8, 16, 24, 32, 40, 48, 56, 64, 72, 80
Elf: 10, 20, 30, 40, 50, 60
Knight, Warrior:  50
Royal, DarkElf: 15, 30

I'll also adjust it so the level used is adjusted by level requirement items, like Opal Jewels and tier bonuses. I think this is a fair way to offset this change.
