### ISSUE TITLE
magic bug on reaper

### ISSUE THREAD

**Issue by injection55** [zajako/LineageHD#268]
soo i turn reaper an i try to learn spells that are above lv 8 an up an but it wounlt let me because it said i dont have the lvs requirements. injection 
 
 
Leave a comment

Attach files by dragging & dropping, selecting or pasting them.

**Comment by zajako** [comment]
This is not a bug, this is due to the changes to level requirements for spellbooks. You can see this here:

https://github.com/zajako/LineageHD/issues/266
