### ISSUE TITLE
Stun Lock

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#273]
I know you closed the last issue, but I wanted to give some more data because something just doesn't feel right.

In the screenshot I'm a Tier 2 Level 74 Knight with 1000 RES, 154 DR, and -148 AC.
I'm in Ant Caves with a few Soldier Ants attacking me.
-debug doesn't even show I'm getting 0 dmg hits ... it registers nothing.
I've got a string of MISS above my head and yet I'm stun locked hard enough that it takes numerous tries to even get an attack timed in between the hit animations.

![Lineage 2019-09-18 21-05-23-503](https://user-images.githubusercontent.com/54756927/65208334-5507d800-da5a-11e9-9f3c-22022363874d.jpg)

**Comment by zajako** [comment]
okay, thanks for making this clarified.  does your character flinch?  Try turning off the miss animation via the options in game see if that helps.

Let me know the answer to these two questions and we can move forward.

**Comment by AeacosL15** [comment]
I checked the box in settings but it still shows Miss above my head.

Yes, I flinch ... assuming you're talking about the hit animation that prevents you from attacking.

**Comment by zajako** [comment]
I put in a change that should only cause flinching when damage is coming through.

**Comment by zajako** [comment]
Can you check if the stun lock from being hit is better now?

**Comment by AeacosL15** [comment]
Still being stun locked while not taking damage.  Even have 248 DR this time.

**Comment by zajako** [comment]
Okay, it’s not being caught where I thought it was then. I’ll figure it out.

**Comment by zajako** [comment]
Another attempt is ready with next test restart

**Comment by AeacosL15** [comment]
Still stun locked in ant caves, at level 87 now.

**Comment by AeacosL15** [comment]
More data:  I went to Skaro and while I would get stun locked from melee, I was not getting stun locked from the archers.

I'm not sure how these evasion numbers play into the calculations, but I've noticed my melee (DG) evasion has been all different kinds of negative numbers.  My ranged (IS) evasion though has always shown as a positive number and a fairly high value.  -stats show ER = 98.  Is it possible to cap the DG at it's max value in order to test it?
![Lineage 2019-09-23 19-38-14-361](https://user-images.githubusercontent.com/54756927/65472677-39297b00-de3a-11e9-9339-4cc30947253e.jpg)

**Comment by zajako** [comment]
Try again.  I made another change.

**Comment by AeacosL15** [comment]
Still stun locked, but also getting some other very strange behavior.  Just in general, sometimes I can attack and sometimes I can't.  If I move, the game shows me moving but the mobs stay where they were at (still hitting me) and I can't attack.  Using /self teleports me back to my original location.  Unable to force attack the storage dwarf in town, but I was able to attack a summoned damage dummy.

**Comment by zajako** [comment]
hmm, that's very weird... all I did was make it so there was now minimal 5% chance of being hit.

I'm gonna try going a custom route then. Maybe making it so that flinching only happens if the damage is high enough percentage of your health or something.

**Comment by zajako** [comment]
See if its still happening now. This change is much more drastic, but it should work.

**Comment by zajako** [comment]
Your other issue about walking around and -self and stuff is now fixed. That was a bug introduced by a change I made.

**Comment by AeacosL15** [comment]
Movement/-self issue is fixed, but still flinching.

At least I can play test again.  :D

**Comment by zajako** [comment]
you're flinching when being delt 0 damage?

I'm pretty sure that shouldn't be possible right now from non magic attacks.

**Comment by AeacosL15** [comment]
-debug registers nothing ... not even 0 dmg hit.  With the series of "Miss" above my head, I assume I'm not getting hit.  Yet I'm doubled over like a kid who ate way too much candy.

![Lineage 2019-09-25 23-41-24-464](https://user-images.githubusercontent.com/54756927/65658767-a847d080-dfee-11e9-8cef-bbcb4d5316b5.jpg)

Current -stats
![Lineage 2019-09-25 23-42-33-163](https://user-images.githubusercontent.com/54756927/65658778-b0077500-dfee-11e9-87dc-13e7af8034a5.jpg)

**Comment by zajako** [comment]
I'm not worried about the stats, I'm doing this at the code that sends the flinch packet.

I'll try again...

**Comment by zajako** [comment]
I just confirmed that its flinching like crazy, however the server isn't sending the flinch packet as far as I can tell, it doesn't make much sense, i'll have to set up further tests.

**Comment by zajako** [comment]
I've found the problem. Its gonna be somewhat complicated to fix, but they apparently made it so there are several attack packets now, each one for different things. Like missing and criticals have their own packet now.

And flinches are assumed now if you do not miss.

**Comment by zajako** [comment]
I believe I have code in place to fix this now. I will restart the test server and try it soon.

**Comment by zajako** [comment]
I can verify now that the stun lock and hit animations are now fixed for no damage attacks.  I'm closing this issue finally.
