### ISSUE TITLE
New SKT Map Issues

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#279]
Matt (Teleporter) not working
No mobs except deer and all of them are named Rudolf (but no red nose ^^)

**Comment by zajako** [comment]
Matt works for me, but all the map locations are displayed as ????

I'll fix the mob spawns though.

**Comment by zajako** [comment]
Spawns are now fixed.

**Comment by zajako** [comment]
Teleporter now has proper popup and the map locations are all in english.
