### ISSUE TITLE
Scatterblaster Freezes Client

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#280]
Occasionally client freezes when using scatterbaster
Seems to be random
Happened several times in different locations
Tried waiting it out twice but client never recovered

**Comment by zajako** [comment]
This is not a crash issue. A crash issue causes the client to close by itself.

Were you running another client (old or new) in the background when this crash happened?

**Comment by Sooleawa2** [comment]
I was not running another client at the time

**Comment by zajako** [comment]
I believe I found the problem, the next server restart should fix this.

**Comment by Sooleawa2** [comment]
Seems to be OK now
