### ISSUE TITLE
Rune upgrades don't consume upgrade passes

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#285]
Got an EXP rune and a few upgrade passes, but upgraded it to max and it didn't consume the passes.

**Comment by zajako** [comment]
how did you upgrade it if the zenos npc doesn't allow you to click on it?

**Comment by zajako** [comment]
I found the bug to this though, it is a bug that is still happening on live apparently,. I've fixed it with the next test server restart.

**Comment by AeacosL15** [comment]
There's approximately 1 pixel, that if you can get your mouse on it just right, the icon turns to the mouth and you can click on him.  NPC is there now though.

**Comment by zajako** [comment]
This is now fixed.
