### ISSUE TITLE
Problem with Hot Keys F5, F9, F11 & F12

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#290]
Whenever I hit one of the hot keys F5, F9, F11 or F12 it changes all of these four keys to the first item in my inventory. Just started happening today.

**Comment by Sooleawa2** [comment]
Seems to happen if I click on any consumable items (pots, scrolls, shots, etc) or armor, weapon and gem. I got it to do this with the entire set of hot keys by placing any of the above in one of the slots and using or equipping it. Did not do it with mage spells.

**Comment by AeacosL15** [comment]
Confirmed this happens with reaper buffs as well.  Same on all 3 hotkey tabs.

**Comment by zajako** [comment]
This is fixed now
