### ISSUE TITLE
Attacks (melee weapon)

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#292]
I can attack the dwarf and damage dummy in town, but I go out to hunt and can't attack anything.

Also, the swing speed is a bit slower than it was yesterday.  Visually it's slower, consumption of soul shots is slower, and DPS on the damage dummy is lower than usual.

**Comment by zajako** [comment]
This should be fixed on test server now. Please Try.

**Comment by AeacosL15** [comment]
Fixed

**Comment by Stardeepp** [comment]
I put the two reaper spells on f keys and then I cant log in on that character anymore.

**Comment by zajako** [comment]
@Stardeepp Private message me on discord and I'll help you fix this.

Also don't reply to a closed ticket with a new bug/issue . That is a good way for me to not be able to find it.
