### ISSUE TITLE
XR weapon, others unequippable

### ISSUE THREAD

**Issue by iiryani** [zajako/LineageHD#302]
Cannot equip certain weapons (polearm/ bow) in CDK - I think the poly only allows certain types of weapons?

**Comment by zajako** [comment]
Polymorphs have always blocked equipping weapons that are not supported.
Switch to pole arm morph to use it, bow to use bow. It was less strict on
old client but still did this.

**Comment by iiryani** [comment]
Is there a CDK for each weapon type? or is CDK now exclusively for sword users?

**Comment by zajako** [comment]
the lightning cdk should be able to equip all weapon types. If it can't I can look into fixing it, but I know it works for both bow and sword, I have yet to test it with pole arm

**Comment by TheNorthernerUkyo** [comment]
So maybe make lightning cdk the default cdk

**Comment by zajako** [comment]
Regular CDK should allow equipping most weapon types too.. Just not the poly dks.
