### ISSUE TITLE
Unable to login with Aeacos (Live)

### ISSUE THREAD

**Issue by AeacosL15** [zajako/LineageHD#305]
Being a fairly low level tier 5, I get the logon buffs.  I start to hear the buff sounds, but they stop/pause and the client crashes.  I can log into other low level chars that get the buffs.

**Comment by AeacosL15** [comment]
From putting NG Soulshots or Faf buff on hotkey

**Comment by zajako** [comment]
more details to add, 

as we tested...

Other characters had no issue with soul shot ng, only the one character and only when put on the hotkeys.


We deleted the soul shots and got new soul shots, so its not the object id.

Other items have similar names so its not the name...

its not the item id as other characters were able to hot key it just the same...

**Comment by AeacosL15** [comment]
Now something else is causing the crash as well.  I left the shots/faf buff off the hotkey bar.  Only difference was instead of escape scrolls, I slotted the T5 knight buff.
