### ISSUE TITLE
Valakas/dragons

### ISSUE THREAD

**Issue by TheNorthernerUkyo** [zajako/LineageHD#335]
no access to valakas lair, and no other dragons in game

**Comment by AeacosL15** [comment]
I've killed all 4 on test .... normal versions and a couple epics.
Valakas - Teleport NPC to what used to be fire valley beach, follow the cliffs to the left and up until you find the 2 NPCs.  One of them teleports you to Valakas' lair.
Antharas - Same as above, other NPC.  Or you can use teleport NPC to Dragon Valley Dungeon.  Same as always from there.
Fafurion - No change.
Lindvior - The scar is still there, but I think it moved a little on the map if you're using your old bookmarks.  Entrance is a little to the right/down if I remember correctly.

**Comment by TheNorthernerUkyo** [comment]
Ya, someone informed me I was an idiot earlier. Thanks.
