### ISSUE TITLE
Tripple Arrow

### ISSUE THREAD

**Issue by Emberglin** [zajako/LineageHD#341]
I cant seem to get tripple arrow to work, if it does work, its not the same as the previous clients and I cant figure it out. Most likely broken.

**Comment by TheNorthernerUkyo** [comment]
It works for me. It may be weapon dependent. I hear it doesnt work with scatterblaster which is technically not a bow.

**Comment by Emberglin** [comment]
Ahhhhh, ok. I'll try it with another bow, ty

**Comment by Emberglin** [comment]
Ok, I tested it more. Tripple arrow only works if your unpollyed or have the dragon morph poly. All other polys dont jive with tripple arrow. It has nothing to do with equipment because it does work with scatterblaster if you are unemployed or dragon morphed. All other bow polys must be fixed.
