### ISSUE TITLE
pouch issue

### ISSUE THREAD

**Issue by iiryani** [zajako/LineageHD#350]
Normally you can store items in the pouch that are non-transferable such as satchels, jewels etc. Right now the satchel does not show these items so they cannot be stored to make space in the regular inventory. The satchel doesn't even show so it is more like a storage dwarf at the moment.

**Comment by iiryani** [comment]
Actually also - I don't know if this is even fixable but normally we can just click all on many items, and when the satchel is full it will still take the items that stack that are already being stored in the satchel. Now, when we try to store items it will reject the entire storage request instead of taking items it has already / can stack & leaving the rest.

**Comment by zajako** [comment]
please test these issues, I believe they should be fixed now.
