### ISSUE TITLE
Can not switch T5 main and sub classes. Hermuncus NPC doesnt work

### ISSUE THREAD

**Issue by Capwne** [zajako/LineageHD#353]
Can not switch T5 main and sub classes. Hermuncus NPC  in -shop doesnt work.

**Comment by zajako** [comment]
I had this fixed, what doesn’t work about it now? Does the text box show up?

**Comment by Capwne** [comment]
Yea the text box doesn’t show up

**Comment by zajako** [comment]
It should be working, I just tested it and it does work just fine.  Try it again, maybe you were disconnected or something.

http://files.zajako.com/2aa672007c7f

If it still doesn't work, re-open this ticket.
