### ISSUE TITLE
Very high GPU and power usage which might cause lineage crashes

### ISSUE THREAD

**Issue by Capwne** [zajako/LineageHD#355]
I have a good desktop window 10 machines. My graphic card is RX 580 (it should be a decent graphic card) and my GPU usage is always 70-80%. Power usage is also very high.

![Capture11](https://user-images.githubusercontent.com/54390884/66373634-ec779100-e95d-11e9-84a7-3802b0ba3911.PNG)

Often time if too much animations then lineage crashes. 

Is there a setting that I need to adjust?

**Comment by zajako** [comment]
This is something built into the binary, you can lower the resolution on the game to lower the gpu pull, but other than that, I'm not sure.

I'm also trying to update the game's binary which should help as well.

I can't really change anything with this though as I don't have the source of the client.


Also here are the recommended hardware options for the HD client:

http://files.zajako.com/72b0a72ced4f
