### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by iiryani** [zajako/LineageHD#36]
Bookmarks appear incorrectly - also all lead to random teleport
![Lineage 2019-03-09 08-47-08-718](https://user-images.githubusercontent.com/48228427/54072427-a97b0100-4248-11e9-808c-9ebba799d16f.jpg)

**Comment by zajako** [comment]
I've fixed the ability to travel to bookmarks with btele and the like. I've also fixed the listing of saved bteles.
