### ISSUE TITLE
Mobs making toon "flinch"

### ISSUE THREAD

**Issue by TheNorthernerUkyo** [zajako/LineageHD#370]
when hunting areas where mobs don't "miss", according to graphic, cause toon to "flinch" or stun even when doing 0 dmg according to -debug. mobs who miss and cause 0 dmg don't make toon flinch.

**Comment by zajako** [comment]
I believe this is now fixed, if not, please re-create the ticket.

**Comment by TheNorthernerUkyo** [comment]
Flinch still happens even when taking 0 damage from mobs
