### ISSUE TITLE
Selecting Elf completely crashes client to desktop

### ISSUE THREAD

**Issue by Samtook** [zajako/LineageHD#373]
My hotkeys were not working.  NB wouldn't work, X pots would disappear from hotkeys.  All while the hotkeys were locked.  Zaj, asked me to restart client.  I did that, but when I re-selected my elf after restart, game crashes to desktop every time now when I select elf.  Basically cannot play it.

**Comment by zajako** [comment]
This issue was fixed, closing the ticket.
