### ISSUE TITLE
Crashing when starting client

### ISSUE THREAD

**Issue by iiryani** [zajako/LineageHD#377]
I can't log onto KingNothing.. but I can log onto other characters on same account. It's been crashing before the character appears in town, but a few times it will stay frozen and show 0 items in inventory before crashing.

**Comment by zajako** [comment]
This is the existing bug with the hotkeys and inventory finally happening to you. The fix is to change your site settings to send hotkeys to no.

I've already done this for you though, so feel free to login and verify it works now.
