### ISSUE TITLE
Underground

### ISSUE THREAD

**Issue by keblrelf** [zajako/LineageHD#380]
The daily quest on. General is skeleton. The star on floor has red x. 
There is also 3 words shillen light. Shillen web and vortex
![20191119_060703](https://user-images.githubusercontent.com/54983395/69144661-c33c3b80-0a99-11ea-99ac-ea23d0cf31bf.jpg)
![20191119_060441](https://user-images.githubusercontent.com/54983395/69144687-d222ee00-0a99-11ea-971b-662e0f36076f.jpg)
![20191119_060417](https://user-images.githubusercontent.com/54983395/69144702-da7b2900-0a99-11ea-97f1-1a9f34ba9c17.jpg)

**Comment by zajako** [comment]
The next restart should fix this issue and replace the animations with much cooler and working sprites.
