### ISSUE TITLE
Pledge members cant see clan chat

### ISSUE THREAD

**Issue by TheNorthernerUkyo** [zajako/LineageHD#384]
New members added since hd client launch can't see clan or alli chat. Existing members from before hd launch can see what new members type though. Also new members can't be seen as online in game clan listing, however they are listed as being in clan.

**Comment by zajako** [comment]
This will be fixed with the next restart. they will likely have to leave clan and rejoin. This is due to the custom clan features not being applied to the new client's clan join. It should be now with next restart.

Thanks for your patience
