### ISSUE TITLE
Died without receiving damage

### ISSUE THREAD

**Issue by Sooleawa2** [zajako/LineageHD#387]
My client crashed when I was on UG1 heading to UG2 (due to inventory bug reported earlier). When I logged back on I was immediately killed, but I had not taken any damage as indicated by my hp bar. There are no mobs on UG1 that can even inflict damage on me. How could this happen?

It would suck if it happens again because my client crashes periodically due to magic animation lag.

Please look into this.

**Comment by zajako** [comment]
After restart, you'll get a 15 second absolute barrier buff to keep you safe to ensure your character fully loads before the monsters can hit you. This should remedy the problem.  If this is abused, I may make it significantly lesser or remove it altogether again.

**Comment by Sooleawa2** [comment]
Thanks. It actually helped me yesterday. I was parked in an area on UG3 I thought would not been an issue when I log in but was surrounded by mobs when I logged in. AB actually popped but it gave me enough time to buff up and set spells. I think I would have been toast without it. The weird thing is that I have enough res so that these mobs can't damage me. I guess I need to buff up for everything to take effect. Anyways, thanks again. Your change seemed to work as intended.
Dave
    On Wednesday, December 11, 2019, 05:02:48 AM EST, zajako <notifications@github.com> wrote:  
 
 
After restart, you'll get a 15 second absolute barrier buff to keep you safe to ensure your character fully loads before the monsters can hit you. This should remedy the problem. If this is abused, I may make it significantly lesser or remove it altogether again.
