### ISSUE TITLE
NPC Link(s) broken to Create and Upgrade 2nd Batch Jewels

### ISSUE THREAD

**Issue by Fawx907** [zajako/LineageHD#393]
Taiven the sky jeweler NPC

Once you click create or upgrade link, there are no options to select.

![image](https://user-images.githubusercontent.com/48227742/81771005-51640e00-948e-11ea-8e3b-4b0929c8f75f.png)

![image](https://user-images.githubusercontent.com/48227742/81771032-6a6cbf00-948e-11ea-945a-3561d1778014.png)

![image](https://user-images.githubusercontent.com/48227742/81771061-7a849e80-948e-11ea-8ae4-883a7edb0ca9.png)

![image](https://user-images.githubusercontent.com/48227742/81771107-9425e600-948e-11ea-9893-2baf626adc7b.png)

![image](https://user-images.githubusercontent.com/48227742/81771131-a30c9880-948e-11ea-8112-d1393cb7bab1.png)

**Comment by zajako** [comment]
I'll be pushing a patch for the client shortly that will fix this, without the need of a restart.
