### ISSUE TITLE
NPC Link(s) broken to Craft Death Items

### ISSUE THREAD

**Issue by Fawx907** [zajako/LineageHD#394]
Francis the Antiquities Expert

Once you click on Craft Death Items link, there are no options to select.

![image](https://user-images.githubusercontent.com/48227742/81771325-24642b00-948f-11ea-8795-01c1be9eb875.png)

![image](https://user-images.githubusercontent.com/48227742/81771344-32b24700-948f-11ea-9ed8-1f3e76948de1.png)

The other options look like this

![image](https://user-images.githubusercontent.com/48227742/81771404-507fac00-948f-11ea-9634-6f0ee6e44f0b.png)

**Comment by zajako** [comment]
This will be fixed with a patch shortly after this reply. I've also remastered all of the other crafting links for this npc so that the required materials are readable.
