### ISSUE TITLE
NPC Link(s) broken to create Ancient Brooch (2 slot)

### ISSUE THREAD

**Issue by Fawx907** [zajako/LineageHD#395]
Pandora NPC

Used to have the option to buy Ancient Brooch for 100 Million Adena.
The link is missing.

![image](https://user-images.githubusercontent.com/48227742/81771496-a3f1fa00-948f-11ea-8ff6-942d8ff65e79.png)

![image](https://user-images.githubusercontent.com/48227742/81771526-b2401600-948f-11ea-84d1-e0da209bebe5.png)

**Comment by zajako** [comment]
I'll be pushing a patch shortly after this reply that will fix this without requiring a server restart. Thanks!
