### ISSUE TITLE
Hands issue w Myl15

### ISSUE THREAD

**Issue by iiryani** [zajako/LineageHD#432]
If you have any time left on hands of fate and you log off to use Myl15 for the event, you will lose all time remaining on hands of fate (and all other buffs). It does not cancel buffs/hands of fate by restarting/closing game and reopening normally.

**Comment by zajako** [comment]
Good catch, I'll look into this, it will need a restart to fix once I find and fix the bug.

**Comment by zajako** [comment]
This should be fixed with the restart coming this morning. If it isn't re-open this ticket.
