### ISSUE TITLE
Cantopen cloent

### ISSUE THREAD

**Issue by zzzmage302** [zajako/LineageHD#433]
I cant open my client it says error cannt opengl got both versions downloaded and the connector just says all 4 servers are offline. The lineagehd is ghe one that says the opengl error.

**Comment by zajako** [comment]
You need to update your video card drivers it sounds like. Or your video card is not supported.

Only the LineageHD client currently will work, make sure you download and install it from www.l15server.com and choose the live server in the server selection list.

**Comment by zzzmage302** [comment]
Now I'm on but when I select character it wont logon it goves me a error

**Comment by zajako** [comment]
I replied to the other ticket that you made for that error. Closing this ticket now
