### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Stardeepp** [zajako/LineageHD#440]
The game glitched while I was playing and after logging off I cant log back in. Also, about a week ago I was no longer able to log into Discord. Discord says it cant accept the invite. Thanks!

**Comment by Stardeepp** [comment]
The screen says please wait but never proceeds to the character screen.

**Comment by zajako** [comment]
Thanks for your patience, I have the server back up and stable.

Here's a new discord invite, just wait in the quarantine channel and I'll approve you: https://discord.gg/YrQ8EqVaPM
