### ISSUE TITLE
Inventory item order gets scrambled.

### ISSUE THREAD

**Issue by sampey6** [zajako/LineageHD#443]
This issue occurs rarely when logging in to a screen that does not load players or NPC after exit and coming back the Characters inventory will become scrambled. Today 1/28/2023 after a server reset that took place around 7:57AM, this inventory scramble occurred on every character on my account. (When this occurs it also resets hot keys to default)

**Comment by zajako** [comment]
I cleared all configs for all players today, this caused your inventory to be scrambled. I cleared the configs due to a bug that was causing the black screen on login. Sorry for the inconvenience.
