### ISSUE TITLE
200m disappeared??

### ISSUE THREAD

**Issue by RaginnFlame** [zajako/LineageHD#444]
I was playing as ragingflame and buying an ancient brooch from Pandora, I brought 300m with me, but after I purchased it, all my money are gone. (I only bought 1)

What is happening? Can you help me check to see what happened? 

I think it happened in the evening of 5/20.

**Comment by zajako** [comment]
I'm restarting to fix this bug right now, after the restart I will restore your 300m adena.

Sorry for the inconvenience!

**Comment by zajako** [comment]
Correction to my previous comment, I don't know who your character is, as usernames don't match from github to L1.5 Please send me a private message on discord so I can know who this is.
