### ISSUE TITLE
Losing HP for no reason 

### ISSUE THREAD

**Issue by RaginnFlame** [zajako/LineageHD#447]
HP kept on jumping back and forth, while losing a percentage until zero, didnt want to die, so I quite before dying.

**Comment by RaginnFlame** [comment]
Do -self to fix, or restart.  Thx to Fawx

**Comment by zajako** [comment]
Some monsters in some areas for some reason get out of sync with the game client, -self and -fix commands will update your position with the client to fix this when this happens, showing the monsters that are hitting you.

Sorry for the inconvenience!
