### ISSUE TITLE
lineage 1.5 website password reset

### ISSUE THREAD

**Issue by brass12** [zajako/LineageHD#476]
I need to have my lineage 1.5 website password reset. Google password manager has blocked my original password because it was found in a data breach.

**Comment by zajako** [comment]
I edited this issue to remove personal information.

**Comment by zajako** [comment]
I can help you reset your password, shoot me a pm on discord @zajako and I'll give you instructions for resetting your password.

**Comment by brass12** [comment]
tyvm i have msged u on discord.

**Comment by zajako** [comment]
I've replied to your message on discord with instructions.

**Comment by brass12** [comment]
ty
